services:
  app:
    container_name: message-backend-app
    image: message-backend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    env_file:
      - .env
    command: npm run start:prod
