version: '3.8'

services:
  app:
    image: nestjs-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run start:prod
